DROP TABLE IF EXISTS Grower CASCADE;
DROP TABLE IF EXISTS Plant CASCADE;
DROP TABLE IF EXISTS Plant_Description CASCADE; 
DROP TABLE IF EXISTS Writer CASCADE;
DROP TABLE IF EXISTS Owned_Plant CASCADE; 
DROP TABLE IF EXISTS Diary CASCADE;